server:
  port: 80

wChat:
  appID: wxc86fcb9788d36e3d
  appSecret: b8970404f64b91721c73a15387e81a33
  gzhName: gh_ab5d4378c71d
  token: shit


spring:
  # 数据库链接配置
  datasource:
    url: jdbc:mysql://localhostm:3306/wx_gpt?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: XSYshibendan1!
    # 链接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 链接池初始化大小
      initial-size: 4
      # 最大活跃数
      max-active: 4
      # 最小空闲数
      min-idle: 1
      # 最大等待时间
      max-wait: 60000
